[package]
name = "wn"
version = "0.1.0"
authors = ["Dennis Merkus <dennis.merkus@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1"

[lib]
path = "src/lib.rs"
